- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: example ec2 key
      ec2_key:
        name: example
        region: ap-south-1
      register: keyout

    - debug:
        var: keyout

    - name: store login key
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample-key.pem
      when: keyout.changed
